import crypto from 'crypto';
import pg from 'pg';
import Stripe from 'stripe';
import { printifyConfigured, printifyCostMapForExternalIds } from './printify-admin-data.js';

const {Pool}=pg;
let pool;
const stripe=process.env.STRIPE_SECRET_KEY?new Stripe(process.env.STRIPE_SECRET_KEY):null;
const db=()=>{if(!pool){if(!process.env.DATABASE_URL)throw new Error('DATABASE_URL is not configured');pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.NODE_ENV==='production'?{rejectUnauthorized:false}:undefined});}return pool;};
function cookies(req){return Object.fromEntries(String(req.headers.cookie||'').split(';').map(v=>v.trim()).filter(Boolean).map(part=>{const i=part.indexOf('=');return[decodeURIComponent(part.slice(0,i)),decodeURIComponent(part.slice(i+1))]}));}
function safeEqual(a,b){a=String(a||'');b=String(b||'');return a.length===b.length&&a.length>0&&crypto.timingSafeEqual(Buffer.from(a),Buffer.from(b));}
function validAdmin(req){const secret=String(process.env.ADMIN_SESSION_SECRET||process.env.ADMIN_PASSWORD||'');if(!secret)return false;const token=cookies(req).wild_sage_admin;if(!token)return false;const p=token.split('.');if(p.length!==3)return false;const expected=crypto.createHmac('sha256',secret).update(`${p[0]}.${p[1]}`).digest('hex');return safeEqual(p[2],expected)&&Number(p[0])>Date.now();}
function auth(req,res,next){return validAdmin(req)?next():res.status(401).json({error:'Admin login required.'});}
const dollars=c=>Number(c||0)/100;
function bounds(month){if(!/^\d{4}-\d{2}$/.test(String(month||'')))throw new Error('Invalid month');const[y,m]=month.split('-').map(Number);const start=new Date(Date.UTC(y,m-1,1)),end=new Date(Date.UTC(y,m,1));return{start,end,startSec:Math.floor(start.getTime()/1000),endSec:Math.floor(end.getTime()/1000)-1,startDate:start.toISOString().slice(0,10),endDate:end.toISOString().slice(0,10)};}
async function allStripeSessions(b){if(!stripe)return{configured:false,sessions:[]};let out=[],starting_after;for(let i=0;i<20;i++){const page=await stripe.checkout.sessions.list({limit:100,created:{gte:b.startSec,lte:b.endSec},...(starting_after?{starting_after}:{})});out.push(...page.data);if(!page.has_more||!page.data.length)break;starting_after=page.data.at(-1).id;}return{configured:true,sessions:out.filter(s=>s.payment_status==='paid'&&s.metadata?.wild_sage_test!=='true'&&s.metadata?.do_not_fulfill!=='true'&&!String(s.id||'').startsWith('cs_test_'))};}
async function stripeFees(b){if(!stripe)return 0;let total=0,starting_after;for(let i=0;i<20;i++){const page=await stripe.balanceTransactions.list({limit:100,created:{gte:b.startSec,lte:b.endSec},...(starting_after?{starting_after}:{})});for(const t of page.data)if(['charge','payment','refund','payment_refund','dispute'].includes(t.type))total+=Number(t.fee||0);if(!page.has_more||!page.data.length)break;starting_after=page.data.at(-1).id;}return dollars(total);}
async function wildSage(month,b){const paid=await allStripeSessions(b),sessions=paid.sessions;let productSales=0,shippingCollected=0,salesTax=0,customerPaid=0,refunds=0;for(const s of sessions){const td=s.total_details||{};const discount=Number(td.amount_discount||0),subtotal=Number(s.amount_subtotal||0);productSales+=Math.max(0,subtotal-discount);shippingCollected+=Number(td.amount_shipping||0);salesTax+=Number(td.amount_tax||0);customerPaid+=Number(s.amount_total||0);}let productCost=0,fulfillmentShipping=0,printifyTax=0,fulfillmentCost=0,matched=0;const orders=[];if(printifyConfigured()&&sessions.length){const map=await printifyCostMapForExternalIds(sessions.map(s=>s.id));for(const s of sessions){const p=map.get(String(s.id));if(!p){orders.push({order:s.id.slice(-10),paid:dollars(s.amount_total),matched:false});continue;}matched++;productCost+=Number(p.productCost||0);fulfillmentShipping+=Number(p.shippingCost||0);printifyTax+=Number(p.taxCost||0);fulfillmentCost+=Number(p.totalCost||0);orders.push({order:s.id.slice(-10),paid:dollars(s.amount_total),matched:true,productCost:Number(p.productCost||0),shippingCost:Number(p.shippingCost||0),fulfillmentCost:Number(p.totalCost||0)});}}
const fees=await stripeFees(b);return{businessSlug:'wild-sage-apparel',businessName:'Wild Sage Apparel',orders:sessions.length,productSales:dollars(productSales),shippingCollected:dollars(shippingCollected),salesTaxCollected:dollars(salesTax),customerPaid:dollars(customerPaid),refunds,processorFees:fees,productCost,fulfillmentShipping,printifyTax,fulfillmentCost,matchedOrders:matched,unmatchedOrders:Math.max(0,sessions.length-matched),source:paid.configured?'Stripe + Printify':'Not connected',orderDetails:orders};}
async function dbBusinesses(month,b){const {rows}=await db().query(`SELECT bu.slug,bu.display_name,COUNT(o.id)::int orders,COALESCE(SUM(o.total),0)::numeric revenue FROM businesses bu LEFT JOIN orders o ON o.business_id=bu.id AND o.ordered_at >= $1 AND o.ordered_at < $2 WHERE bu.slug NOT IN ('sage-ember-holdings','wild-sage-apparel') GROUP BY bu.id,bu.slug,bu.display_name ORDER BY bu.display_name`,[b.start,b.end]);return rows.map(r=>({businessSlug:r.slug,businessName:r.display_name,orders:r.orders,productSales:Number(r.revenue||0),shippingCollected:0,salesTaxCollected:0,customerPaid:Number(r.revenue||0),refunds:0,processorFees:0,productCost:0,fulfillmentShipping:0,printifyTax:0,fulfillmentCost:0,matchedOrders:r.orders,unmatchedOrders:0,source:'HQ database'}));}
function occurrences(e,month){const[y,m]=month.split('-').map(Number),start=new Date(String(e.expense_date).slice(0,10)+'T00:00:00');if(Number.isNaN(start.getTime())||e.active===false)return 0;const monthStart=new Date(y,m-1,1),monthEnd=new Date(y,m,0,23,59,59);if(start>monthEnd)return 0;if(!e.recurring)return String(e.expense_date).slice(0,7)===month?1:0;const f=String(e.frequency||'monthly').toLowerCase();if(f==='monthly')return 1;if(f==='annual'||f==='yearly')return start.getMonth()===m-1?1:0;if(f==='quarterly'){const d=(y-start.getFullYear())*12+(m-1-start.getMonth());return d>=0&&d%3===0?1:0;}if(f==='weekly'){let d=new Date(start),n=0;while(d<monthStart)d.setDate(d.getDate()+7);while(d<=monthEnd){n++;d.setDate(d.getDate()+7);}return n;}return 1;}
async function operatingExpenses(month){const {rows}=await db().query(`SELECT e.*,b.slug business_slug,b.display_name business_name FROM expenses e JOIN businesses b ON b.id=e.business_id WHERE e.active IS DISTINCT FROM false`);const out=new Map();for(const e of rows){const n=occurrences(e,month);if(!n)continue;const amount=Number(e.amount||0)*n;if(!out.has(e.business_slug))out.set(e.business_slug,{operatingExpenses:0,startupCosts:0,expenseItems:[]});const x=out.get(e.business_slug),startup=String(e.category||'').toLowerCase()==='startup / opening cost';if(startup)x.startupCosts+=amount;else x.operatingExpenses+=amount;x.expenseItems.push({vendor:e.vendor||'',category:e.category||'',description:e.description||'',amount,recurring:Boolean(e.recurring)});}return out;}
async function report(month){const b=bounds(month);const[wild,others,expenses]=await Promise.all([wildSage(month,b),dbBusinesses(month,b),operatingExpenses(month)]);const businesses=[wild,...others].map(r=>{const ex=expenses.get(r.businessSlug)||{operatingExpenses:0,startupCosts:0,expenseItems:[]};const grossRevenue=r.productSales+r.shippingCollected-r.refunds;const cogs=r.fulfillmentCost;const grossProfit=grossRevenue-cogs;const operatingExpenses=ex.operatingExpenses+r.processorFees;const netProfit=grossProfit-operatingExpenses;const margin=grossRevenue?netProfit/grossRevenue*100:0;return{...r,...ex,grossRevenue,cogs,grossProfit,operatingExpenses,netProfit,margin,reconciled:r.unmatchedOrders===0};});const parent=expenses.get('sage-ember-holdings')||{operatingExpenses:0,startupCosts:0,expenseItems:[]};const totals={orders:businesses.reduce((n,r)=>n+r.orders,0),productSales:businesses.reduce((n,r)=>n+r.productSales,0),shippingCollected:businesses.reduce((n,r)=>n+r.shippingCollected,0),salesTaxCollected:businesses.reduce((n,r)=>n+r.salesTaxCollected,0),customerPaid:businesses.reduce((n,r)=>n+r.customerPaid,0),grossRevenue:businesses.reduce((n,r)=>n+r.grossRevenue,0),processorFees:businesses.reduce((n,r)=>n+r.processorFees,0),cogs:businesses.reduce((n,r)=>n+r.cogs,0),operatingExpenses:businesses.reduce((n,r)=>n+r.operatingExpenses,0)+parent.operatingExpenses,startupCosts:businesses.reduce((n,r)=>n+r.startupCosts,0)+parent.startupCosts,netProfit:businesses.reduce((n,r)=>n+r.netProfit,0)-parent.operatingExpenses};totals.margin=totals.grossRevenue?totals.netProfit/totals.grossRevenue*100:0;return{month,generatedAt:new Date().toISOString(),totals,parentExpenses:parent,businesses,reconciliation:{status:businesses.every(r=>r.reconciled)?'reconciled':'attention',unmatchedOrders:businesses.reduce((n,r)=>n+r.unmatchedOrders,0),notes:['Sales tax collected is shown separately and excluded from revenue/profit.','Startup costs are tracked separately from normal monthly operating expenses.','Wild Sage processor and Printify costs are matched automatically when source records are available.','Other DBA costs use the HQ expense ledger until direct payment/fulfillment integrations are connected.']}};}
export function registerMonthlyPnlRoutes(app){app.get('/api/holding/monthly-pnl',auth,async(req,res)=>{try{const month=/^\d{4}-\d{2}$/.test(String(req.query.month||''))?String(req.query.month):new Date().toISOString().slice(0,7);res.json(await report(month));}catch(e){console.error('Monthly P&L error',e);res.status(500).json({error:e.message||'Unable to build monthly P&L.'});}});}
