import crypto from 'crypto';
import Stripe from 'stripe';

const stripe=process.env.STRIPE_SECRET_KEY?new Stripe(process.env.STRIPE_SECRET_KEY):null;
function cookies(req){return Object.fromEntries(String(req.headers.cookie||'').split(';').map(v=>v.trim()).filter(Boolean).map(part=>{const i=part.indexOf('=');return[decodeURIComponent(part.slice(0,i)),decodeURIComponent(part.slice(i+1))]}));}
function secret(){return process.env.ADMIN_SESSION_SECRET||process.env.ADMIN_PASSWORD||'';}
function sign(payload){return crypto.createHmac('sha256',secret()).update(payload).digest('hex');}
function validAdmin(req){const token=cookies(req).wild_sage_admin;if(!secret()||!token)return false;const p=token.split('.');if(p.length!==3)return false;const expected=sign(`${p[0]}.${p[1]}`),actual=p[2];return expected.length===actual.length&&crypto.timingSafeEqual(Buffer.from(expected),Buffer.from(actual))&&Number(p[0])>Date.now();}
function auth(req,res,next){return validAdmin(req)?next():res.status(401).json({error:'Admin login required.'});}
const dollars=c=>Number(c||0)/100;
function monthBounds(month){if(!/^\d{4}-\d{2}$/.test(String(month||'')))throw new Error('Invalid month');const [y,m]=month.split('-').map(Number),start=Math.floor(new Date(Date.UTC(y,m-1,1)).getTime()/1000),end=Math.floor(new Date(Date.UTC(y,m,1)).getTime()/1000)-1;return{start,end};}
async function checkoutSessions(start,end){if(!stripe)return[];let out=[],starting_after;for(let i=0;i<20;i++){const page=await stripe.checkout.sessions.list({limit:100,created:{gte:start,lte:end},...(starting_after?{starting_after}:{})});out.push(...page.data);if(!page.has_more||!page.data.length)break;starting_after=page.data.at(-1).id;}return out.filter(s=>s.payment_status==='paid'&&s.metadata?.wild_sage_test!=='true'&&s.metadata?.do_not_fulfill!=='true'&&!String(s.id||'').startsWith('cs_test_'));}
async function registrationStatus(){if(!stripe)return{configured:false,registrations:[]};try{const page=await stripe.tax.registrations.list({limit:100});return{configured:true,registrations:page.data.map(r=>({id:r.id,country:r.country,countryOptions:r.country_options,status:r.status,activeFrom:r.active_from,expiresAt:r.expires_at||null}))};}catch(e){return{configured:true,registrations:[],warning:'Stripe Tax registrations could not be read yet.'};}}
async function reportFor(month){const{start,end}=monthBounds(month),sessions=await checkoutSessions(start,end);const rows=sessions.map(s=>{const td=s.total_details||{},tax=Number(td.amount_tax||0),shipping=Number(td.amount_shipping||0),discount=Number(td.amount_discount||0),total=Number(s.amount_total||0),subtotal=Number(s.amount_subtotal||0),productSales=Math.max(0,subtotal-discount);return{id:s.id,date:new Date(s.created*1000).toISOString(),customer:s.customer_details?.name||'',email:s.customer_details?.email||s.customer_email||'',productSales:dollars(productSales),shipping:dollars(shipping),tax:dollars(tax),discount:dollars(discount),customerPaid:dollars(total),automaticTax:s.automatic_tax?.enabled===true,status:s.automatic_tax?.status||null};});return{month,orders:rows.length,productSales:rows.reduce((n,r)=>n+r.productSales,0),shippingCollected:rows.reduce((n,r)=>n+r.shipping,0),salesTaxCollected:rows.reduce((n,r)=>n+r.tax,0),discounts:rows.reduce((n,r)=>n+r.discount,0),customerPaid:rows.reduce((n,r)=>n+r.customerPaid,0),rows};}
export function registerSalesTaxRoutes(app){app.get('/api/holding/sales-tax',auth,async(req,res)=>{try{if(!stripe)return res.status(503).json({error:'Stripe is not configured.'});const month=/^\d{4}-\d{2}$/.test(String(req.query.month||''))?String(req.query.month):new Date().toISOString().slice(0,7);const [report,registration]=await Promise.all([reportFor(month),registrationStatus()]);res.json({...report,registration,notes:['Sales tax is excluded from operating revenue in this report.','Refund-adjusted tax should be verified against Stripe Tax filing reports before remittance.']});}catch(e){res.status(500).json({error:e.message||'Unable to load sales tax report.'});}});
app.get('/api/holding/sales-tax/ytd',auth,async(req,res)=>{try{if(!stripe)return res.status(503).json({error:'Stripe is not configured.'});const year=Number(req.query.year)||new Date().getFullYear(),last=year===new Date().getFullYear()?new Date().getMonth()+1:12,reports=[];for(let m=1;m<=last;m++)reports.push(await reportFor(`${year}-${String(m).padStart(2,'0')}`));res.json({year,months:reports.map(r=>({month:r.month,orders:r.orders,productSales:r.productSales,shippingCollected:r.shippingCollected,salesTaxCollected:r.salesTaxCollected,customerPaid:r.customerPaid})),totals:{orders:reports.reduce((n,r)=>n+r.orders,0),productSales:reports.reduce((n,r)=>n+r.productSales,0),shippingCollected:reports.reduce((n,r)=>n+r.shippingCollected,0),salesTaxCollected:reports.reduce((n,r)=>n+r.salesTaxCollected,0),customerPaid:reports.reduce((n,r)=>n+r.customerPaid,0)}});}catch(e){res.status(500).json({error:e.message||'Unable to load YTD sales tax.'});}});}
