import 'dotenv/config';
import express from 'express';
import crypto from 'crypto';
import Stripe from 'stripe';
import path from 'path';
import fs from 'fs/promises';
import { fileURLToPath } from 'url';
import { registerAdminRoutes } from './admin.js';
import { registerProductCollectionRoutes } from './product-collections.js';
import { registerOrderDetailRoutes } from './order-details.js';
import { registerAccountingRoutes } from './accounting.js';
import { registerCustomerOrderRoutes } from './customer-orders.js';
import { registerOrderManagementRoutes,getFriendlyOrderNumber } from './order-management.js';
import { registerSeoRoutes } from './seo-pages.js';
import { registerTestCheckoutRoutes } from './test-checkout.js';
import { registerParentDashboardRoutes } from './parent-dashboard-api.js';
import { registerPasswordVaultRoutes } from './password-vault-api.js';
import { registerDatabaseDiagnosticsRoutes } from './database-diagnostics.js';
import { registerHQOperationsRoutes } from './hq-operations.js';
import { registerProfitBreakdownRoutes } from './profit-breakdown-api.js';
import { registerSinSageRoutes } from './sin-sage-api.js';
import { registerMonthlyCloseRoutes } from './monthly-close-api.js';
import { registerMediaRoutes } from './media-uploads.js';

const app=express();const __dirname=path.dirname(fileURLToPath(import.meta.url));const PORT=Number(process.env.PORT||3000);const API_BASE='https://api.printify.com/v1';let resolvedShopId=null;const stripe=process.env.STRIPE_SECRET_KEY?new Stripe(process.env.STRIPE_SECRET_KEY):null;const liveFulfillmentDryRun=()=>String(process.env.LIVE_FULFILLMENT_DRY_RUN||'').toLowerCase()==='true';
app.use(express.json({limit:'14mb',verify:(req,_res,buf)=>{req.rawBody=buf;}}));registerMediaRoutes(app);registerAdminRoutes(app);registerProductCollectionRoutes(app);registerOrderDetailRoutes(app);registerAccountingRoutes(app);registerCustomerOrderRoutes(app);registerOrderManagementRoutes(app);registerTestCheckoutRoutes(app);registerParentDashboardRoutes(app);registerPasswordVaultRoutes(app);registerDatabaseDiagnosticsRoutes(app);registerHQOperationsRoutes(app);registerProfitBreakdownRoutes(app);registerSinSageRoutes(app);registerMonthlyCloseRoutes(app);registerSeoRoutes(app);app.use(express.static(path.join(__dirname,'public')));app.get('/admin',(_req,res)=>res.sendFile(path.join(__dirname,'public','admin.html')));app.get('/order-lookup',(_req,res)=>res.sendFile(path.join(__dirname,'public','order-lookup.html')));app.get('/holding',async(_req,res)=>{try{const file=await fs.readFile(path.join(__dirname,'public','holding-dashboard.html'),'utf8');res.type('html').send(file.replace('</body>','<script src="/holding-diagnostics.js"></script><script src="/hq-operations-client.js"></script><script src="/tax-report-client.js"></script><script src="/profit-breakdown-client.js"></script><script src="/hq-alerts-client.js"></script><script src="/monthly-close-client.js"></script></body>'));}catch{res.sendFile(path.join(__dirname,'public','holding-dashboard.html'));}});app.get('/order-confirmation',(_req,res)=>res.sendFile(path.join(__dirname,'public','order-confirmation.html')));
const money=c=>Number(c||0)/100;
async function printify(pathname,options={}){const token=process.env.PRINTIFY_API_TOKEN;if(!token||token==='replace_me')throw new Error('PRINTIFY_API_TOKEN is not configured');const res=await fetch(`${API_BASE}${pathname}`,{...options,headers:{Authorization:`Bearer ${token}`,'User-Agent':'WildSageApparel/0.1','Content-Type':'application/json;charset=utf-8',...(options.headers||{})}});const body=await res.text();let data;try{data=body?JSON.parse(body):null}catch{data=body}if(!res.ok){const e=new Error(`Printify ${res.status}`);e.status=res.status;e.detail=data;throw e}return data;}
async function getShopId(){if(resolvedShopId)return resolvedShopId;const shops=await printify('/shops.json'),list=Array.isArray(shops)?shops:(shops?.data||[]);if(!list.length)throw new Error('No Printify shops are available for this token');const shop=list.find(s=>String(s.title||s.name||'').trim().replace(/\s+/g,' ').toLowerCase()==='wild sage apparel');if(!shop)throw new Error('Wild Sage Apparel Printify shop was not found.');resolvedShopId=String(shop.id);return resolvedShopId;}
function normalizeProduct(p){const enabled=(p.variants||[]).filter(v=>v.is_enabled!==false),purchasable=enabled.filter(v=>v.is_available!==false),prices=purchasable.map(v=>v.price).filter(Number.isFinite),images=(p.images||[]).map(i=>({src:i.src,variantIds:i.variant_ids||[],position:i.position||'front'}));return{id:p.id,title:p.title,description:p.description||'',tags:p.tags||[],visible:p.visible!==false,blueprintId:p.blueprint_id,printProviderId:p.print_provider_id,minPrice:prices.length?money(Math.min(...prices)):0,images,variants:enabled.map(v=>({id:v.id,title:v.title,sku:v.sku||'',price:money(v.price),cost:money(v.cost),options:v.options||{},available:v.is_available!==false}))};}
function stripeShippingAddress(session){const shipping=session?.collected_information?.shipping_details||session?.shipping_details,details=shipping||session?.customer_details,address=details?.address;if(!address)throw new Error('Stripe checkout did not include a shipping address.');return{first_name:String(details?.name||'Customer').trim().split(/\s+/)[0]||'Customer',last_name:String(details?.name||'').trim().split(/\s+/).slice(1).join(' ')||'-',email:session?.customer_details?.email||'',phone:session?.customer_details?.phone||'',country:address.country||'US',region:address.state||'',address1:address.line1||'',address2:address.line2||'',city:address.city||'',zip:address.postal_code||''};}
async function findPrintifyOrderByExternalId(shopId,externalId){const data=await printify(`/shops/${shopId}/orders.json?limit=100`),orders=Array.isArray(data)?data:(data?.data||[]);return orders.find(o=>String(o.external_id||'')===String(externalId))||null;}
async function fulfillPaidStripeSession(session){if(!session||session.payment_status!=='paid')throw new Error('Stripe session is not paid; Printify fulfillment blocked.');if(String(session.id||'').startsWith('cs_test_')||session.metadata?.wild_sage_test==='true'||session.metadata?.do_not_fulfill==='true')throw new Error('Test orders are blocked from Printify fulfillment.');if(liveFulfillmentDryRun()){console.log(`LIVE FULFILLMENT DRY RUN: ${session.id} paid successfully; Printify creation intentionally skipped.`);return{id:null,external_id:session.id,status:'dry-run',dryRun:true,message:'Live payment verified; Printify fulfillment intentionally skipped.'};}const raw=session.metadata?.printify_items;if(!raw)throw new Error('Stripe session is missing Printify item metadata.');let items;try{items=JSON.parse(raw)}catch{throw new Error('Stripe session contains invalid Printify item metadata.')}const shopId=await getShopId(),externalId=session.id;let order=await findPrintifyOrderByExternalId(shopId,externalId);if(!order){order=await printify(`/shops/${shopId}/orders.json`,{method:'POST',body:JSON.stringify({external_id:externalId,label:`Wild Sage ${externalId.slice(-8)}`,line_items:items.map(x=>({product_id:x.productId,variant_id:Number(x.variantId),quantity:Math.max(1,Number(x.quantity||1))})),shipping_method:1,send_shipping_notification:true,address_to:stripeShippingAddress(session)})});}const status=String(order?.status||'').toLowerCase();if(!['in-production','in_production','production','fulfilled','shipped','canceled','cancelled'].includes(status)&&order?.id)await printify(`/shops/${shopId}/orders/${encodeURIComponent(order.id)}/send_to_production.json`,{method:'POST'});return order;}
app.get('/api/health',(_req,res)=>res.json({ok:true,store:process.env.STORE_NAME||'Wild Sage Apparel'}));app.get('/api/setup-status',async(_req,res)=>{try{const shopId=await getShopId();res.json({printifyConnected:true,shopId,stripeConnected:Boolean(stripe),stripeWebhookConfigured:Boolean(process.env.STRIPE_WEBHOOK_SECRET),liveFulfillmentDryRun:liveFulfillmentDryRun()})}catch(err){res.status(502).json({printifyConnected:false,detail:err.message,liveFulfillmentDryRun:liveFulfillmentDryRun()})}});
app.get('/api/products',async(_req,res)=>{try{const shopId=await getShopId(),data=await printify(`/shops/${shopId}/products.json?limit=50`),raw=Array.isArray(data)?data:(data.data||[]);res.json({source:'printify',products:raw.map(normalizeProduct).filter(p=>p.visible)})}catch(err){res.status(502).json({error:'Unable to load Printify products',detail:err.detail||err.message})}});app.get('/api/products/:id',async(req,res)=>{try{const shopId=await getShopId(),p=await printify(`/shops/${shopId}/products/${encodeURIComponent(req.params.id)}.json`);res.json(normalizeProduct(p))}catch(err){res.status(err.status||502).json({error:'Unable to load product'})}});
app.post('/api/checkout',async(req,res)=>{if(!stripe)return res.status(503).json({error:'Stripe is not configured.'});const{items}=req.body||{};if(!Array.isArray(items)||!items.length)return res.status(400).json({error:'Your bag is empty.'});try{const shopId=await getShopId(),lineItems=[],orderItems=[];for(const item of items){const product=await printify(`/shops/${shopId}/products/${encodeURIComponent(item.productId)}.json`),variant=(product.variants||[]).find(v=>String(v.id)===String(item.variantId)&&v.is_enabled!==false&&v.is_available!==false);if(!variant)throw new Error(`A selected option for "${product.title}" is no longer available.`);const quantity=Math.max(1,Math.min(10,Number(item.quantity||1))),image=product.images?.find(i=>(i.variant_ids||[]).includes(Number(variant.id)))?.src||product.images?.[0]?.src;lineItems.push({price_data:{currency:'usd',unit_amount:Number(variant.price),product_data:{name:product.title,description:variant.title,...(image?{images:[image]}:{})}},quantity});orderItems.push({productId:product.id,variantId:Number(variant.id),quantity});}const origin=process.env.PUBLIC_STORE_URL||`${req.protocol}://${req.get('host')}`,cartId=crypto.randomUUID(),session=await stripe.checkout.sessions.create({mode:'payment',line_items:lineItems,success_url:`${origin}/order-confirmation?session_id={CHECKOUT_SESSION_ID}`,cancel_url:`${origin}/?checkout=cancelled`,shipping_address_collection:{allowed_countries:['US']},phone_number_collection:{enabled:true},billing_address_collection:'auto',customer_creation:'always',client_reference_id:cartId,metadata:{cart_id:cartId,printify_items:JSON.stringify(orderItems)}});res.json({url:session.url})}catch(err){res.status(400).json({error:err.message||'Unable to start checkout.'})}});
app.post('/api/webhooks/stripe',async(req,res)=>{if(!stripe||!process.env.STRIPE_WEBHOOK_SECRET)return res.status(503).send('Stripe webhook is not configured.');let event;try{event=stripe.webhooks.constructEvent(req.rawBody,req.headers['stripe-signature'],process.env.STRIPE_WEBHOOK_SECRET)}catch{return res.status(400).send('Invalid Stripe webhook signature.')}if(['checkout.session.completed','checkout.session.async_payment_succeeded'].includes(event.type)&&event.data.object.payment_status==='paid'){try{await getFriendlyOrderNumber(event.data.object.id);await fulfillPaidStripeSession(event.data.object)}catch(err){console.error(err);return res.status(500).send('Fulfillment failed; Stripe may retry this webhook.')}}res.sendStatus(200);});
app.get('/api/checkout-status/:sessionId',async(req,res)=>{if(!stripe)return res.status(503).json({error:'Stripe is not configured.'});try{const s=await stripe.checkout.sessions.retrieve(req.params.sessionId);res.json({sessionId:s.id,orderNumber:await getFriendlyOrderNumber(s.id),paymentStatus:s.payment_status,status:s.status,fulfilled:s.payment_status==='paid',liveFulfillmentDryRun:liveFulfillmentDryRun()})}catch{res.status(400).json({error:'Unable to verify checkout status.'})}});app.post('/api/orders',async(req,res)=>{if(!stripe)return res.status(503).json({error:'Stripe is not configured.'});try{const s=await stripe.checkout.sessions.retrieve(req.body?.sessionId);if(s.payment_status!=='paid')return res.status(402).json({error:'Stripe has not confirmed payment.'});await getFriendlyOrderNumber(s.id);res.status(201).json(await fulfillPaidStripeSession(s))}catch(err){res.status(502).json({error:'Order fulfillment failed',detail:err.message})}});app.post('/api/webhooks/printify',(req,res)=>{console.log('Printify webhook:',req.body?.type||req.body?.topic||'event');res.sendStatus(200)});
const base=()=>String(process.env.PUBLIC_STORE_URL||'https://wild-sage-storefront.onrender.com').replace(/\/$/,'');app.get('/robots.txt',(_req,res)=>res.type('text/plain').send(`User-agent: *\nAllow: /\nDisallow: /admin\nDisallow: /holding\nDisallow: /api/\nSitemap: ${base()}/sitemap.xml\n`));
app.get('/*splat',(_req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));app.listen(PORT,()=>console.log(`Wild Sage storefront running at http://localhost:${PORT}`));