import test from 'node:test';import assert from 'node:assert/strict';import express from 'express';import crypto from 'crypto';import fs from 'node:fs/promises';import {PGlite} from '@electric-sql/pglite';import {registerToteRentalRoutes} from '../tote-rentals.js';
test('payments: confirmed capacity, authenticated checkout, delayed webhook, duplicates and deposit refund',async()=>{
 const pg=new PGlite();await pg.exec(`CREATE TABLE businesses(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),slug text UNIQUE,legal_name text,display_name text,business_type text,status text,updated_at timestamptz DEFAULT now());CREATE TABLE sites(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),business_id uuid,slug text UNIQUE,name text,domain text,dashboard_url text,platform text,status text);CREATE TABLE orders(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),business_id uuid,site_id uuid,external_order_id text,friendly_order_number text,status text,total numeric,fulfillment_provider text,fulfillment_status text,metadata jsonb,updated_at timestamptz DEFAULT now(),UNIQUE(business_id,external_order_id));`);
 for(const f of ['012_tote_rentals.sql','014_tote_payments.sql','014_tote_payments.sql','015_tote_booking_deposits.sql','016_tote_cancellations.sql'])await pg.exec(await fs.readFile(new URL('../database/'+f,import.meta.url),'utf8'));
 const adapter={query:(s,a)=>pg.query(s,a),connect:async()=>({query:(s,a)=>pg.query(s,a),release(){}})};
 let creates=0,refunds=0,session,checkoutParams;
 const stripe={checkout:{sessions:{create:async(params,options)=>{creates++;checkoutParams=params;assert.match(options.idempotencyKey,/totes-/);session={id:'cs_test_local_'+creates,url:'https://checkout.stripe.com/qa',status:'open',currency:'usd',amount_total:19500,payment_status:'unpaid',payment_intent:'pi_qa',metadata:params.metadata};return session;},retrieve:async()=>session,expire:async()=>{session.status='expired';return session;}}},paymentIntents:{retrieve:async()=>({latest_charge:{amount_refunded:0}})},refunds:{retrieve:async()=>({id:'re_qa',status:'succeeded',metadata:{source:'tote-rentals'}}),create:async params=>{refunds++;assert.equal(params.amount,5000);return {id:'re_qa',status:'succeeded'};}}};
 process.env.ADMIN_SESSION_SECRET='local-qa';process.env.STRIPE_WEBHOOK_SECRET='local-webhook';const app=express();app.use(express.json());const handleEvent=registerToteRentalRoutes(app,{database:adapter,paymentClient:stripe});const server=app.listen(0),base=`http://127.0.0.1:${server.address().port}`;const payload=`${Date.now()+60000}.nonce`,sig=crypto.createHmac('sha256','local-qa').update(payload).digest('hex'),cookie=`wild_sage_admin=${payload}.${sig}`;
 const req=async(url,method='GET',body,auth=true)=>{const r=await fetch(base+url,{method,headers:{'Content-Type':'application/json',...(auth?{Cookie:cookie}:{})},...(body?{body:JSON.stringify(body)}:{})});return {status:r.status,data:await r.json()};};
 try{
 const today=(await req('/api/totes/admin')).data.today;
 assert.equal((await req('/api/totes/settings','PATCH',{brand:'QA',totalTotes:40,totalDollies:2,damagedTotes:0,damagedDollies:0,deliveryArea:'QA',depositAmount:50,depositTerms:'Refund after inspection; agreed deductions for damage or loss.'})).status,200);
 const request={name:'QA',email:'local@example.test',phone:'8015550100',startDate:today,totes:20,dollies:1,weeks:1,delivery:true,deliveryAddress:'QA only',acceptTerms:true};await req('/api/totes/requests','POST',request,false);let b=(await req('/api/totes/admin')).data.bookings[0],id=b.id;
 assert.equal((await req(`/api/totes/bookings/${id}/checkout`,'POST',{taxAmount:10,amountsReviewed:true},false)).status,401);
 assert.equal((await req(`/api/totes/bookings/${id}/checkout`,'POST',{taxAmount:10,amountsReviewed:true})).status,400);
 assert.equal((await req(`/api/totes/bookings/${id}`,'PATCH',{status:'confirmed'})).status,200);
 assert.equal((await req(`/api/totes/availability?startDate=${today}&weeks=1`)).data.totes,20);
 assert.equal((await req(`/api/totes/bookings/${id}/checkout`,'POST',{taxAmount:10,amountsReviewed:false})).status,400);
 assert.equal((await req(`/api/totes/bookings/${id}/checkout`,'POST',{taxAmount:10,amountsReviewed:true})).status,200);
 assert.deepEqual(checkoutParams.line_items.map(x=>x.price_data.unit_amount),[13500,1000,5000]);assert.equal(checkoutParams.payment_method_types,undefined);
 assert.equal((await req(`/api/totes/bookings/${id}/checkout`,'POST',{})).status,200);assert.equal(creates,1);
 assert.equal((await req(`/api/totes/bookings/${id}`,'PATCH',{status:'cancelled'})).status,400);
 assert.equal((await req(`/api/totes/bookings/${id}`,'PATCH',{paymentStatus:'paid'})).status,400);
 await handleEvent({type:'checkout.session.completed',data:{object:session}});assert.equal((await req('/api/totes/admin')).data.bookings[0].payment_status,'unpaid');
 session.status='complete';session.payment_status='paid';const paid={type:'checkout.session.async_payment_succeeded',data:{object:session}};
 await assert.rejects(handleEvent({...paid,data:{object:{...session,amount_total:1}}}),/mismatch/);
 await handleEvent(paid);await handleEvent(paid);assert.equal((await req('/api/totes/admin')).data.bookings[0].payment_status,'paid');assert.equal(Number((await pg.query('SELECT total FROM orders')).rows[0].total),135);assert.equal((await req(`/api/totes/bookings/${id}/refresh-payment`,'POST',{})).status,200);
 assert.equal((await req(`/api/totes/bookings/${id}/refund-deposit`,'POST',{confirm:true})).status,400);
 await req(`/api/totes/bookings/${id}`,'PATCH',{status:'out'});await req(`/api/totes/bookings/${id}`,'PATCH',{status:'cleaning',returnedTotes:20,returnedDollies:1,damagedTotes:0,damagedDollies:0});assert.equal((await req('/api/totes/admin')).data.ready.totes,20);
 await req(`/api/totes/bookings/${id}`,'PATCH',{status:'completed'});assert.equal((await req('/api/totes/admin')).data.ready.totes,40);
 assert.equal((await req(`/api/totes/bookings/${id}/refund-deposit`,'POST',{confirm:true})).data.refund.status,'succeeded');await req(`/api/totes/bookings/${id}/refund-deposit`,'POST',{confirm:true});assert.equal(refunds,1);assert.equal(Number((await pg.query('SELECT total FROM orders')).rows[0].total),135);
 await handleEvent({type:'charge.refunded',data:{object:{payment_intent:'pi_qa',amount_refunded:19500}}});await handleEvent(paid);assert.equal((await req('/api/totes/admin')).data.bookings[0].payment_status,'refunded');assert.equal(Number((await pg.query('SELECT total FROM orders')).rows[0].total),0);
 await req('/api/totes/requests','POST',request,false);const second=(await req('/api/totes/admin')).data.bookings.find(x=>x.id!==id).id;await req(`/api/totes/bookings/${second}`,'PATCH',{status:'confirmed'});await req(`/api/totes/bookings/${second}/checkout`,'POST',{taxAmount:10,amountsReviewed:true});session.status='complete';await handleEvent({type:'checkout.session.async_payment_failed',data:{object:session}});assert.equal((await req(`/api/totes/bookings/${second}/checkout`,'POST',{taxAmount:10,amountsReviewed:true})).status,200);assert.equal(creates,3);assert.equal((await req(`/api/totes/bookings/${second}/void-checkout`,'POST',{})).status,200);assert.equal((await req(`/api/totes/bookings/${second}`,'PATCH',{status:'cancelled'})).status,200);assert.equal((await req('/api/totes/admin')).data.ready.totes,40);
 assert.equal(await handleEvent({type:'checkout.session.completed',data:{object:{metadata:{source:'apparel'}}}}),false);
 }finally{server.close();await pg.close();}
});
