import test from 'node:test';import assert from 'node:assert/strict';import express from 'express';import crypto from 'crypto';import fs from 'node:fs/promises';import {PGlite} from '@electric-sql/pglite';import {registerToteRentalRoutes} from '../tote-rentals.js';
test('online booking: stock holds, $35 credit, $8 damage bill, cancellation refunds and expired holds',async()=>{
const pg=new PGlite();await pg.exec(`CREATE TABLE businesses(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),slug text UNIQUE,legal_name text,display_name text,business_type text,status text,updated_at timestamptz DEFAULT now());CREATE TABLE sites(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),business_id uuid,slug text UNIQUE,name text,domain text,dashboard_url text,platform text,status text);CREATE TABLE orders(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),business_id uuid,site_id uuid,external_order_id text,friendly_order_number text,status text,total numeric,fulfillment_provider text,fulfillment_status text,metadata jsonb,updated_at timestamptz DEFAULT now(),UNIQUE(business_id,external_order_id));`);for(const f of ['012_tote_rentals.sql','014_tote_payments.sql','015_tote_booking_deposits.sql','015_tote_booking_deposits.sql'])await pg.exec(await fs.readFile(new URL('../database/'+f,import.meta.url),'utf8'));
const sessions=new Map(),refunds=new Map();let n=0,refundCalls=0;const stripe={checkout:{sessions:{create:async params=>{const id='cs_test_'+(++n),s={id,url:'https://checkout.stripe.com/'+id,status:'open',payment_status:'unpaid',amount_total:params.line_items.reduce((v,x)=>v+x.price_data.unit_amount*x.quantity,0),currency:'usd',metadata:params.metadata,payment_intent:'pi_'+n};sessions.set(id,s);return s;},retrieve:async id=>sessions.get(id),expire:async id=>{sessions.get(id).status='expired';}}},refunds:{create:async p=>{refundCalls++;const r={id:'re_'+refundCalls,status:'succeeded',metadata:p.metadata};refunds.set(r.id,r);return r;},retrieve:async id=>refunds.get(id)}};
const adapter={query:(s,a)=>pg.query(s,a),connect:async()=>({query:(s,a)=>pg.query(s,a),release(){}})};process.env.ADMIN_SESSION_SECRET='booking-test';process.env.STRIPE_WEBHOOK_SECRET='booking-webhook';const app=express();app.use(express.json());const event=registerToteRentalRoutes(app,{database:adapter,paymentClient:stripe});const server=app.listen(0),base=`http://127.0.0.1:${server.address().port}`,payload=`${Date.now()+60000}.nonce`,cookie='wild_sage_admin='+payload+'.'+crypto.createHmac('sha256','booking-test').update(payload).digest('hex');const req=async(u,m='GET',b,auth=false)=>{const r=await fetch(base+u,{method:m,headers:{'Content-Type':'application/json',...(auth?{Cookie:cookie}:{})},...(b?{body:JSON.stringify(b)}:{})});return {status:r.status,data:await r.json()};};
try{const today=(await req('/api/totes/admin','GET',null,true)).data.today;await req('/api/totes/settings','PATCH',{brand:'Wild Roots QA',totalTotes:40,totalDollies:2,damagedTotes:0,damagedDollies:0,deliveryArea:'QA'},true);const body={name:'QA',email:'qa@example.test',phone:'8015550100',startDate:today,totes:20,dollies:1,weeks:1,delivery:true,deliveryAddress:'QA only',acceptTerms:true};
const a=await req('/api/totes/reserve','POST',body);assert.equal(a.status,201);const token=a.data.manageUrl.split('=')[1],first=sessions.get('cs_test_1');assert.equal(first.amount_total,3500);assert.equal((await req(`/api/totes/public-availability?startDate=${today}&weeks=1`)).data.totes,20);assert.equal((await req('/api/totes/reserve','POST',{...body,totes:30})).status,409);let b=(await pg.query('SELECT * FROM tote_rentals WHERE manage_token=$1',[token])).rows[0];assert.equal((await req('/api/totes/bookings/'+b.id,'PATCH',{status:'out'},true)).status,400);
first.payment_status='paid';first.status='complete';await event({type:'checkout.session.completed',data:{object:first}});await event({type:'checkout.session.completed',data:{object:first}});let view=(await req('/api/totes/manage/'+token)).data;assert.equal(view.paidCents,3500);assert.equal(view.balanceCents,10000);
await req('/api/totes/bookings/'+b.id,'PATCH',{status:'out'},true);assert.equal(Number((await pg.query('SELECT total FROM orders WHERE external_order_id=$1',[b.id])).rows[0].total),35);await req('/api/totes/bookings/'+b.id,'PATCH',{status:'cleaning',returnedTotes:20,returnedDollies:1,damagedTotes:1,damagedDollies:0},true);view=(await req('/api/totes/manage/'+token)).data;assert.equal(view.damageCents,800);assert.equal(view.balanceCents,10800);assert.equal((await req('/api/totes/bookings/'+b.id+'/final-balance','POST',{taxAmount:0,amountsReviewed:true},true)).status,200);const final=sessions.get('cs_test_2');assert.equal(final.amount_total,10800);final.status='complete';final.payment_status='paid';await event({type:'checkout.session.completed',data:{object:final}});view=(await req('/api/totes/manage/'+token)).data;assert.equal(view.balanceCents,0);assert.equal(view.paidCents,14300);await req('/api/totes/bookings/'+b.id,'PATCH',{status:'completed'},true);assert.equal(Number((await pg.query('SELECT total FROM orders WHERE external_order_id=$1',[b.id])).rows[0].total),143);
const second=await req('/api/totes/reserve','POST',body);const t2=second.data.manageUrl.split('=')[1],s2=sessions.get('cs_test_3');s2.payment_status='paid';s2.status='complete';await event({type:'checkout.session.completed',data:{object:s2}});assert.equal((await req('/api/totes/manage/'+t2+'/cancel','POST',{confirm:true})).status,200);assert.equal((await req('/api/totes/manage/'+t2+'/cancel','POST',{confirm:true})).status,200);assert.equal(refundCalls,1);view=(await req('/api/totes/manage/'+t2)).data;assert.equal(view.refundedCents,3500);assert.equal(view.balanceCents,0);assert.equal((await req(`/api/totes/public-availability?startDate=${today}&weeks=1`)).data.totes,39);
const third=await req('/api/totes/reserve','POST',body);const t3=third.data.manageUrl.split('=')[1];await pg.query("UPDATE tote_rentals SET hold_until=now()-interval '1 minute' WHERE manage_token=$1",[t3]);assert.equal((await req(`/api/totes/public-availability?startDate=${today}&weeks=1`)).data.totes,39);assert.equal((await req('/api/totes/manage/'+t3)).data.status,'cancelled');assert.equal((await req('/api/totes/manage/bad')).status,404);
}finally{server.close();await pg.close();}
});
